### PR TITLE
Add parsing reel urls in amp-instagram

### PR DESCRIPTION
**Pull request by dominikdassow**

### CODE REVIEW

**Comment by dominikdassow** [comment]
@magyarandras I can't figure out why the tests fail. The converted and expected output seems to be the same:
https://github.com/magyarandras/amp-converter/runs/6306273081?check_suite_focus=true#step:5:45

Do you know why and how to fix it?

**Comment by magyarandras** [comment]
> @magyarandras I can't figure out why the tests fail. The converted and expected output seems to be the same: https://github.com/magyarandras/amp-converter/runs/6306273081?check_suite_focus=true#step:5:45
> 
> Do you know why and how to fix it?

@dominikdassow

In your input HTML, you have whitespace between the blockquote and script tag and the converter removes the script tag, but keeps the whitespace, so there will be whitespace in the output after the `</amp-instagram>` tag.
You can remove the whitespace between the two tags(`</blockquote> <script` => `</blockquote><script`) in the input string and the tests will succeed as expected. In most cases, you can also trim the result before checking equality in the tests.

I know this behavior can be weird, but for the browsers/HTML parsers, it doesn't matter whether the converter keeps the whitespace or not. Maybe I can add a feature in the future that compresses the HTML output by removing whitespaces and line breaks. It is also possible to write tests that use an HTML parser instead of direct string comparisons.

I hope my answer is useful!

By the way thanks for your contribution!

**Comment by dominikdassow** [comment]
Thanks for the quick and helpful response! I've removed the whitespace and the tests are passing now.

**Comment by magyarandras** [comment]
I merged it.

**Comment by magyarandras** [comment]
The fix has been added to the v1.0.7 release.

**Pull request merged**
